export type FailureCode =
  | 'INSUFFICIENT_FUNDS' | 'REVERSAL_INSUFFICIENT_FUNDS' | 'CURRENCY_MISMATCH'
  | 'WALLET_IDENTITY_MISMATCH' | 'REFERENCE_MISMATCH' | 'REFERENCE_KIND_INVALID'
  | 'REFERENCE_NOT_PROCESSED' | 'REFERENCE_NOT_FOUND' | 'REVERSAL_ALREADY_APPLIED'
  | 'AMOUNT_MISMATCH' | 'AMOUNT_OUT_OF_RANGE' | 'INFRASTRUCTURE_PERMANENT_FAILURE';
